/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.notify

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import java.util.*

class NotifyApi(val client: HttpClient, private val token: String, private val basePath: String = "/") {

    /**
     * Авторизация с помощью JWT
     * @param body
     * @return Tokens
     */
    suspend fun notify(userId: String, title: String, message: String, priority: Int = 0) {
        val response = client.post("${basePath}message") {
            parameter("token", token)
            this.contentType(ContentType.Application.Json)
            setBody(
                """
                {
                    "id": ${UUID.randomUUID()},
                    "title": "$title",
                    "message": "$message",
                    "priority": $priority,
                    "extras": {
                        "receiver::options": {
                            "userid": "$userId"
                        }
                    }
                }
            """.trimIndent()
            )
        }
        println(response.status)
        println(response.bodyAsText())
        return when (response.status.value) {
            in (200..299) -> {}
            else -> throw RuntimeException(response.bodyAsText())
        }
    }
}
