/**
 * University Data Service
 * Сервис по работе с университетскими данными
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.university.client.apis

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.http.*
import api.university.client.models.AddAuditoryRequest
import api.university.client.models.AuditoryDTO

class AuditoryControllerApi(
    private val httpClient: HttpClient,
    private val basePath: String = "http://localhost:8080"
) {

    /**
     *
     *
     * @param body
     * @return AuditoryDTO
     */
    suspend fun addAuditory(body: AddAuditoryRequest): AuditoryDTO {
        val response = httpClient.post("$basePath/api/auditory") {
            contentType(ContentType.Application.Json)
            setBody(body)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<AuditoryDTO>()
            else -> throw IllegalStateException("${response.status}")
        }
    }

    /**
     *
     *
     * @return kotlin.Array<AuditoryDTO>
     */
    suspend fun getAuditories(): List<AuditoryDTO> {
        val response = httpClient.get("$basePath/api/auditory") {
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<List<AuditoryDTO>>()
            else -> throw IllegalStateException("${response.status}")
        }
    }
}
