/**
 * University Data Service
 * Сервис по работе с университетскими данными
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.university.client.apis

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.http.*
import api.university.client.models.AddDepartmentRequest
import api.university.client.models.DepartmentDto

class DepartmentControllerApi(
    private val httpClient: HttpClient,
    private val basePath: String = "http://localhost:8080"
) {

    /**
     *
     *
     * @param body
     * @return DepartmentDto
     */
    suspend fun addDepartment(body: AddDepartmentRequest): DepartmentDto {
        val response = httpClient.post("${basePath}api/departments") {
            contentType(ContentType.Application.Json)
            setBody(body)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<DepartmentDto>()
            else -> throw IllegalStateException("${response.status}")
        }
    }

    /**
     *
     *
     * @return kotlin.Array<DepartmentDto>
     */
    suspend fun getDepartments(): List<DepartmentDto> {
        val response = httpClient.get("${basePath}api/departments")
        return when (response.status) {
            HttpStatusCode.OK -> response.body<List<DepartmentDto>>()
            else -> throw IllegalStateException("${response.status}")
        }
    }
}
