version: "3.8"
services:
  gateway:
    restart: on-failure
    container_name: ASTU-Gateway
    build:
      context: .
    image: astu/gateway:v1
    ports:
      - "80:8082"
    networks:
      - services-network
      - internet
    env_file:
      - .env
  gotify:
    image: gotify/server
    ports:
      - "8081:80"
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
networks:
  services-network:
    driver: bridge
    name: private-astu-services-network
#    internal: true
  internet:
    driver: bridge