/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.request.client.models

import kotlinx.serialization.Serializable


/**
 * 
 * @param requirementTypeId 
 * @param name 
 * @param description 
 * @param isMandatory 
 */
@Serializable
data class AddRequirementDTO (

    val requirementTypeId: String,
    val name: String,
    val description: String,
    val isMandatory: Boolean
)