/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.universal_request.client.models

import kotlinx.serialization.Serializable


/**
 * 
 * @param id 
 * @param name 
 */
@Serializable
data class TemplateDTO(val id: String, val name: String, val description: String, val fields: List<String>)
