/**
 * ChatService API
 * ChatService API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.chat.client.models

import kotlinx.serialization.Serializable


/**
 * 
 * @param userId 
 * @param role 
 */
@Serializable
data class ChatMemberDTO (val userId: String, val role: String)