/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.auth.client.apis

import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*

class DefaultApi(val client: HttpClient, private val basePath: String = "/") {

    /**
     * Получение идентификатора пользователя
     * @return UserInfo
     */
    suspend fun getId(authHeader: String): String {
        val response = client.get("${basePath}token-validate") {
            header("Authorization", authHeader)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.bodyAsText()
            else -> throw RuntimeException()
        }
    }
}
