/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package api.auth.client.apis

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.http.*
import api.auth.client.models.Tokens

class GoogleApi(val client: HttpClient, private val basePath: String = "/") {

    /**
     * Авторизация через google аккаунт
     * @return Tokens
     */
    suspend fun googleLoginGet(): Tokens {
        val response = client.get("${basePath}google/login") {}
        return when (response.status) {
            HttpStatusCode.OK -> response.body<Tokens>()
            else -> throw RuntimeException()
        }
    }

    /**
     * Привязка пользователя с Google OAuth2
     * @return Tokens
     */
    suspend fun googleRegistrationGet(tokens: Tokens): Tokens {
        val response = client.get("${basePath}google/registration") {
            this.header(HttpHeaders.Authorization, tokens.accessToken)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<Tokens>()
            else -> throw RuntimeException()
        }
    }
}
